branches:
  only:
    - master
    
configuration: release

version: 0.0.0.{build}
image: Visual Studio 2017

cache:
  - packages -> **\packages.config

artifacts:
  - path: '**/*.msi' 
    name: Installers
  - path: 'Android Log Viewer Portable.zip'
    name: PortableApplication

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'

build:
  verbosity: normal
  project: AndroidLogViewer.sln

before_build:
  - cmd: nuget restore

after_build:
  - cmd: 7z a "Android Log Viewer Portable.zip" %APPVEYOR_BUILD_FOLDER%\AndroidLogViewer\bin\Release\*.exe

deploy:
  - provider: GitHub
    release: Android Log Viewer $(appveyor_build_version)
    description: 'Android Log Viewer release for version $(appveyor_build_version)'
    draft: true
    auth_token: 
      secure: fw8xGdlviNruXruf81HaAXKFPLfMkslVjV5gfJMxGmY3CHlpZWtFp+4w2TF0f+wT
    on: 
      APPVEYOR_REPO_TAG: true

init:
  # Set "build version number" from the tag name when applicable
  - ps: >-
      if ($env:APPVEYOR_REPO_TAG -eq "true" -and $env:APPVEYOR_REPO_TAG.StartsWith("v"))
          {
            Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
          }
